### ISSUE TITLE
Queries resolve in 404 errors, but data source says connection is OK

### ISSUE THREAD

**Issue by keck-in-space** [yamcs/grafana-yamcs#13]
We are having an issue with v2.2.2 of the plugin on YAMCS 5.5.2. When we configure the data source, we get a "YAMCS connection OK" message and we are able to see the parameters for our instance when we use the query creator inside a panel. However, when we try to fetch the parameter data, we get a "No data" warning, and upon inspecting the query, we see that we have a 404 error with the following content.

```html
<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
```

Are these two versions compatible? Is there anything else I can try? The v1.0.0 of the plugin has been working fine, but we need some of the features of v2.2.2

**Comment by keck-in-space** [comment]
Also tested on v2.2.1, with the same result.

**Comment by fqqb** [comment]
I did a quick test, and it is working for me. Make sure to enter the instance name in the connection settings.

What URL is being tried? Do you see any activity in the Yamcs log? Because that html does not look like it comes from Yamcs.

That said, this version of Yamcs is ~2 years old, so if it happens to not work, so be it.

**Comment by keck-in-space** [comment]
The instance name is in the settings. The data source is saying the connection is fine, and I can see the telemetry parameters from the panel query constructor view, so there is some kind of connection being made.

I'll try to send the URL that is being tried, but I will need to redact a few things, so please let me know if it is still useful.

```
<server_name>:8090/api/datasources/proxy/22/api/mdb/<instance_name>/parameters/%2F<instance_name>%2F<parameter_name>
```

![image](https://user-images.githubusercontent.com/32853381/234280978-605afebb-07a0-4c59-adee-4e53caf99683.png)

**Comment by fqqb** [comment]
Ah i see now. I believe this HTML response is generated by an intermediate Apache server.

Please check that AllowEncodedSlashes is on for the path. As you can see in the URL there are some references to `%2F` which Apache, by default, does not handle very well.

More here: https://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes

(previous versions probably used slashes instead of %2F, but that has its own bunch of issues).

**Comment by keck-in-space** [comment]
Hmm interesting. We aren't running Apache on the server we're connecting to. There should be nothing between us and YAMCS. I'm not really sure how we could be getting this 404 if it isn't coming from YAMCS. If you're out of ideas and don't want to further investigate, feel free to close this.

**Comment by keck-in-space** [comment]
Is there a commit somewhere you could point to that doesn't require %2F that still has the engineering value feature so we could install from source?

**Comment by fqqb** [comment]
I don't see a commit, but you could try to replace all occurrences of

```
const encodedName = encodeURIComponent(parameter);
```

to 

```
const encodedName = parameter.slice(1);
```

in this file: https://github.com/yamcs/grafana-yamcs/blob/master/src/YamcsClient.ts, and see if that works any better for you.

(removing the encodeURIComponent will keep the slashes un-encoded, but you must slice(1) to remove the very first slash, because otherwise you will have two successive slashes in the final URL.





For information, I can reproduce very similar output from a random Apache server, so that part remains supicious to me:

```
< HTTP/1.1 404 Not Found
< Date: Wed, 26 Apr 2023 17:17:41 GMT
< Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
< Content-Length: 210
< Keep-Alive: timeout=5, max=100
< Connection: Keep-Alive
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /blablabla was not found on this server.</p>
</body></html>
```

**Comment by fqqb** [comment]
There was also this issue: #11
But not sure it applies to you, since you have an old Yamcs server, and also say 2.2.1 doesn't work.

**Comment by keck-in-space** [comment]
Thanks for the additional help. I can't really debug the Apache server stuff any further as my sysadmin has said Apache isn't running on the YAMCS server so really out of ideas there...

I'll try the find and replace on the YamcsClient.ts file. Does this need to be done to every instance of `encodeURIComponent` or just the ones that are referencing a `parameter` variable? I see a line that references `this.instance` using `encodeURIComponent` in that file.

**Comment by fqqb** [comment]
For instance, should be fine either way. I don't think that will make a difference in the final URL.

**Comment by keck-in-space** [comment]
Thanks. We'll give this a shot and report back

**Comment by xpromache** [comment]
> Thanks for the additional help. I can't really debug the Apache server stuff any further as my sysadmin has said Apache isn't running on the YAMCS server so really out of ideas there...
> 

If you stop Yamcs and run your query, do you still get a 404 (instead of connection refused)?

**Comment by keck-in-space** [comment]
We currently don't have the bandwidth to support further debugging of this. Thanks for all the help! Sorry we couldn't track it all the way down. We are just going with a different solution internally to display engineering units.
