### ISSUE TITLE
Plugin not working on Grafana 7.2

### ISSUE THREAD

**Issue by h-roon** [yamcs/grafana-yamcs#6]
Hello! I am having trouble getting this plugin to work. I tried installing through the CLI but I get a 404 error saying that the yamcs-datasource plugin does not exist. I pulled down a list of the plugins and indeed it was not there. I then attempted to go through the developer branch and follow those instructions. I made it all the way to the end but I do not see a yamcs-datasource option when I go to add a datasource. Am I doing something wrong or is this version of Grafana not supported yet?

**Comment by fqqb** [comment]
Hi thanks for reaching out.
First: if you work with a clone, update it to latest master, I pushed some tweaks to make it run better (reverted partially developed features).

grafana-cli by default downloads from grafana.com, however this datasource plugin is not yet available from the grafana.com marketplace. We once requested to publish v1.0.0, but following a plugin id rename, and generally slow approval process of Grafana (they manually confirm each version), I'm not quite sure anymore if we want to continue going through that process while this plugin is still to be considered 'under construction'.

I've updated the repository README so that this is a little more clear for a first reader. My recommendation is to clone this repository directly into your grafana plugin directory (master branch), and update from time to time to pull in the latest changes.

Your final comment is that you did not see the Yamcs datasource when trying to add a datasource as an admin. Before debugging further, can you check these two things:

- Ensure to restart Grafana, it scans the plugin directory only when it starts (it should also log any plugin ids that it finds)
- Make sure that you are using the right plugin directory. On a tarball installation this is typically just `./data/plugins`. You should also be able to confirm the appropriate plugin directory from Grafana's log output.

**Comment by h-roon** [comment]
Thanks for the speedy response, I tried re-installing with the cli and it works great now! Thanks again!
